### ISSUE TITLE
Add feature to allow user add their owned image editors with ease

### ISSUE THREAD

**Issue by minhthuanit** [weta-vn/advance_image_picker#20]
@weta-vn
Hi guys!
I really love your package, then i'm using that for the next projects.
I pull request to suggest a feature to allow user add their image editor with ease.
Hope it useful for you.
Thank you very much.
https://github.com/weta-vn/advance_image_picker/pull/19

Below is sample screen that i added two new external image editors.

![image](https://user-images.githubusercontent.com/1695979/132098495-fca7786b-cc9f-49b6-96fb-3cb475c64359.png)

**Comment by weta-vn** [comment]
@minhthuanit
Thanks for your supports.
That's really a great idea, that combine plugin's features & preset image editors with user's owned widget easily.
We'll review then release your implementation in the next release version.
Hope more help from you in the future.
