### ISSUE TITLE
Move and Resize

### ISSUE THREAD

**Issue by apocalipse9** [weta-vn/advance_image_picker#24]
Hi Folks, please how to perform move and resize after photo selection?
Something like WhatsApp profile image?

**Comment by minhthuanit** [comment]
@apocalipse9 I think you can use Crop/Scale feature in Image Editor.

**Comment by rydmike** [comment]
The crop and scale features should inded help, here is an example of how you can use them in the image picker.

https://user-images.githubusercontent.com/39990307/134784772-2a99f725-1d59-472c-96d6-e43f436f5a2e.mov
