### ISSUE TITLE
Issue : Denying the authorisation leads to a black screen forever

### ISSUE THREAD

**Issue by VuillaumeGautier** [weta-vn/advance_image_picker#37]
Hi !

Some of our users have been reporting an unclear situation : when they deny the camera or the gallery picker, they're faced against a black screen content, making the information unclear.
Either asking again for the authorization or display the information clearly would fix this, no idea if this is planned or possible through a way.

Thanks !

**Comment by weta-vn** [comment]
Dear @VuillaumeGautier 
We confirmed that denying the authorization leads to a black screen.
We catch authorization exception, then show request permission to allow user do it again (except when user force to don't show permission dialog again, in this case, user must grant permission in OS setting or reinstall app).
We released modified code in v0.1.5+5.
Thank you.
