### ISSUE TITLE
Suddenly, the project cannot be started. I haven't made any changes. It can be used normally before. The following is the error reported. Thank you for your efforts. I like this plug-in very much!

### ISSUE THREAD

**Issue by guolidaxian** [weta-vn/advance_image_picker#40]
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\Camera.java:23: ����: �Ҳ�������
import android.media.EncoderProfiles;
                    ^
  ����:   �� EncoderProfiles
  λ��: ����� android.media
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\Camera.java:935: ����: �Ҳ�������
  EncoderProfiles getRecordingProfile() {
  ^
  ����:   �� EncoderProfiles
  λ��: �� Camera
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:10: ����: �Ҳ�������
import android.media.EncoderProfiles;
                    ^
  ����:   �� EncoderProfiles
  λ��: ����� android.media
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:29: ����: �Ҳ�������
  private EncoderProfiles recordingProfile;
          ^
  ����:   �� EncoderProfiles
  λ��: �� ResolutionFeature
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:63: ����: �Ҳ�������
  public EncoderProfiles getRecordingProfile() {
         ^
  ����:   �� EncoderProfiles
  λ��: �� ResolutionFeature
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:187: ����: �Ҳ�������
  public static EncoderProfiles getBestAvailableCamcorderProfileForResolutionPreset(
                ^
  ����:   �� EncoderProfiles
  λ��: �� ResolutionFeature
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\media\MediaRecorderBuilder.java:8: ����: �Ҳ�������
import android.media.EncoderProfiles;
                    ^
  ����:   �� EncoderProfiles
  λ��: ����� android.media
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\media\MediaRecorderBuilder.java:24: ����: �Ҳ�������
  private final EncoderProfiles encoderProfiles;
                ^
  ����:   �� EncoderProfiles
  λ��: �� MediaRecorderBuilder
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\media\MediaRecorderBuilder.java:36: ����: �Ҳ�������
      @NonNull EncoderProfiles encoderProfiles, @NonNull String outputFilePath) {
               ^
  ����:   �� EncoderProfiles
  λ��: �� MediaRecorderBuilder
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\media\MediaRecorderBuilder.java:51: ����: �Ҳ�������
      @NonNull EncoderProfiles encoderProfiles,
               ^
  ����:   �� EncoderProfiles
  λ��: �� MediaRecorderBuilder
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:186: ����: �Ҳ�������
  @TargetApi(Build.VERSION_CODES.S)
                                ^
  ����:   ���� S
  λ��: �� VERSION_CODES
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\Camera.java:208: ����: ��MediaRecorderBuilder�����ò���ȷ
      mediaRecorderBuilder = new MediaRecorderBuilder(getRecordingProfileLegacy(), outputFilePath);
                             ^
  MediaRecorderBuilder �еĹ����� MediaRecorderBuilder(CamcorderProfile,String) �� MediaRecorderBuilder �еĹ����� MediaRecorderBuilder(EncoderProfiles,String) ��ƥ��
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:118: ����: �Ҳ�������
      EncoderProfiles profile =
      ^
  ����:   �� EncoderProfiles
  λ��: �� ResolutionFeature
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:120: ����: �����EncoderProfiles������
      List<EncoderProfiles.VideoProfile> videoProfiles = profile.getVideoProfiles();
                          ^
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:121: ����: �����EncoderProfiles������
      EncoderProfiles.VideoProfile defaultVideoProfile = videoProfiles.get(0);
                     ^
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:200: ����: �Ҳ�������
          return CamcorderProfile.getAll(cameraIdString, CamcorderProfile.QUALITY_HIGH);
                                 ^
  ����:   ���� getAll(String,int)
  λ��: �� CamcorderProfile
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:204: ����: �Ҳ�������
          return CamcorderProfile.getAll(cameraIdString, CamcorderProfile.QUALITY_2160P);
                                 ^
  ����:   ���� getAll(String,int)
  λ��: �� CamcorderProfile
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:208: ����: �Ҳ�������
          return CamcorderProfile.getAll(cameraIdString, CamcorderProfile.QUALITY_1080P);
                                 ^
  ����:   ���� getAll(String,int)
  λ��: �� CamcorderProfile
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:212: ����: �Ҳ�������
          return CamcorderProfile.getAll(cameraIdString, CamcorderProfile.QUALITY_720P);
                                 ^
  ����:   ���� getAll(String,int)
  λ��: �� CamcorderProfile
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:216: ����: �Ҳ�������
          return CamcorderProfile.getAll(cameraIdString, CamcorderProfile.QUALITY_480P);
                                 ^
  ����:   ���� getAll(String,int)
  λ��: �� CamcorderProfile
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:220: ����: �Ҳ�������
          return CamcorderProfile.getAll(cameraIdString, CamcorderProfile.QUALITY_QVGA);
                                 ^
  ����:   ���� getAll(String,int)
  λ��: �� CamcorderProfile
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:224: ����: �Ҳ�������
          return CamcorderProfile.getAll(cameraIdString, CamcorderProfile.QUALITY_LOW);
                                 ^
  ����:   ���� getAll(String,int)
  λ��: �� CamcorderProfile
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:241: ����: �����EncoderProfiles������
      List<EncoderProfiles.VideoProfile> videoProfiles = recordingProfile.getVideoProfiles();
                          ^
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\features\resolution\ResolutionFeature.java:243: ����: �����EncoderProfiles������
      EncoderProfiles.VideoProfile defaultVideoProfile = videoProfiles.get(0);
                     ^
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\media\MediaRecorderBuilder.java:32: ����: ��MediaRecorderBuilder�����ò���ȷ
    this(camcorderProfile, outputFilePath, new MediaRecorderFactory());
    ^
  MediaRecorderBuilder �еĹ����� MediaRecorderBuilder(CamcorderProfile,String,MediaRecorderFactory) �� MediaRecorderBuilder �еĹ����� MediaRecorderBuilder(EncoderProfiles,String,MediaRecorderFactory) ��ƥ��
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\media\MediaRecorderBuilder.java:79: ����: �����EncoderProfiles������
      EncoderProfiles.VideoProfile videoProfile = encoderProfiles.getVideoProfiles().get(0);
                     ^
F:\workspase\flutter_windows_2.5.0-stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.9.4+4\android\src\main\java\io\flutter\plugins\camera\media\MediaRecorderBuilder.java:80: ����: �����EncoderProfiles������
      EncoderProfiles.AudioProfile audioProfile = encoderProfiles.getAudioProfiles().get(0);
                     ^
27 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':camera:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10m 16s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by guolidaxian** [comment]
Has been solved, thank you! Use the following methods to solve：

dependency_overrides:
  camera: 0.9.3 #advance_image_picker

**Comment by guolidaxian** [comment]
Has been solved, thank you! Use the following methods to solve：

dependency_overrides:
camera: 0.9.3

**Comment by minhthuanit** [comment]
@guolidaxian 
Thank you very much.
I think new updates of camera package wasn't compatible with your project settings.
