### ISSUE TITLE
Member not found: 'ImageCropper.cropImage'

### ISSUE THREAD

**Issue by sulemancipher** [weta-vn/advance_image_picker#43]
I have copied and pasted same code which is given in example section. But it is showing the 
Error: Member not found: 'ImageCropper.cropImage'.
              ImageCropper.cropImage(
                           ^^^^^^^^^

**Comment by masreplay** [comment]
any updates!

**Comment by weta-vn** [comment]
@sulemancipher 
Thank you for your report.
A updated dependence made some compile errors.
We fixed at latest version.
Please confirm.
Thank you.
