### ISSUE TITLE
 I/ExifInterface_JNI(10726): Raw image not detected

### ISSUE THREAD

**Issue by Atn803** [weta-vn/advance_image_picker#8]
I got this issue in the pick image screen. Everytime I try to choose an image the debug console returns the issue as the title says hence I cannot display images.

Edit: The issue exists when I used the newest version. The previous one does not seem to have this issue

**Comment by weta-vn** [comment]
@Atn803
What's about device you tested?

**Comment by Atn803** [comment]
I was using android emulator on Android Studio and Bluestacks 5. Have not tested on real devices yet but I guess something went wrong with my emulators. Also is there a way I can get all the paths after choosing multiple images? I can only get the path of the last chosen picture. I followed your example on [this advance_image_picker example](https://pub.dev/packages/advance_image_picker)

**Comment by weta-vn** [comment]
Thanks @Atn803 
With android, we support official emulator & real devices with minSdkVersion 21.
We don't test on BlueStacks yet and don't have plan to support it in future.
Please use real devices to test your app.

> I can only get the path of the last chosen picture.
With this code, you can get all of selected paths
imageFiles.addAll(objects
        .map((e) => e.modifiedPath)
        .toList());

Thank you very much.
